### ISSUE TITLE
too long waiting

### ISSUE THREAD

**Issue by MaxJan2010** [Japkeerat/YouTube-Videos-Downloader#1]
hi
i waited for more than 10 minutes to download a video 1:13 minutes and it didn't work.
i is still loading ...........
can you please solve this issue
thanks in-advance for your kindly support.

**Comment by Japkeerat** [comment]
Hi!
I checked the code and did a trial run to download a 5-minute video and it worked flawlessly. Please check your internet connectivity.
The video is by default downloaded in the same directory where you keep the code. The webpage shows refreshing until the video is downloaded completely.
I know this is not a great tool but was sufficient for me to download the videos after the extensions failed to download some videos. I don't plan to make improvements on this project and you are free to fork and make a pull request.

**Comment by Japkeerat** [comment]
I am closing this issue. If it still persists, please make an issue again.
